### ISSUE TITLE
Is there a way to get better performance on m2 Macs?

### ISSUE THREAD

**Issue by alextoddslick** [gri573/rethinking-voxels#142]
Believe it or not most if not all shaders are running better on my m2 Max MacBook Pro than my razor blade 8 core 2070 super Max q but when it comes to this shader I see huge frame rate difference. For example complementary normally does in the same word files 90 FPS (same settings and all) for the Mac and 60-70 FPS on my razerblade. Do you know if it is because of the cuda cores or something that is hindering the Mac from getting "normal fps"

I also realized that I didn't state the frame rate of the shader packs between the two,
Mac: 15 FPS
Windows: 45-65 FPS

**Comment by Bipbip2109** [comment]
Top 10 ways to get better performance if you have a Mac : 

Number 1 - Get something else than a Mac

Thanks for watching, please rate 5 stars and subscribe 👍

**Comment by gri573** [comment]
> Top 10 ways to get better performance if you have a Mac :
> 
> Number 1 - Get something else than a Mac
> 
> Thanks for watching, please rate 5 stars and subscribe +1

I used to agree to this, but ever since M1, macs are actually super fast

**Comment by gri573** [comment]
> Believe it or not most if not all shaders are running better on my m2 Max MacBook Pro than my razor blade 8 core 2070 super Max q but when it comes to this shader I see huge frame rate difference. For example complementary normally does in the same word files 90 FPS (same settings and all) for the Mac and 60-70 FPS on my razerblade. Do you know if it is because of the cuda cores or something that is hindering the Mac from getting "normal fps"
> 
> I also realized that I didn't state the frame rate of the shader packs between the two, Mac: 15 FPS Windows: 45-65 FPS

I'm aware of the issue that M1 macs have performance problems with rethinking voxels. I don't think there's a solution to it, because it probably boils down to a few hardware-related aspects and the inner workings of rethinking voxels:

when using complementary, you are probably CPU-limited on your razerblade, and M2 macs have unparalleled performance in workloads with low thread counts (like minecraft's rendering), which puts them at an advantage. However, Rethinking Voxels is much more GPU intensive, which is good for the razerblade, as the 2070 super is faster than the M2 graphics card. This is just a guess, but integer performance (which is something rethinking voxels needs quite a lot) may also vary across graphics cards, causing inconsistent performance.

**Comment by alextoddslick** [comment]
Is it possible to use Apple's Metal API to use their "Mesh Shaders" ([Link to reference](https://developer.apple.com/metal/))? Is that even something Minecraft can do? I do remember hearing that Minecraft was "Metal Optimized" or something but I am not 100% sure the context of that meaning.

**Comment by gri573** [comment]
That's not something a shader can do, but a shader loader might (with quite a hight amount of effort)
