### ISSUE TITLE
Emissive Mob Resource Packs not functioning 

### ISSUE THREAD

**Issue by FryoKnight** [gri573/rethinking-voxels#144]
Been playing with this Shader and have been loving it. Was looking to add in Tissou's Zombie Pack. While it properly replaces the Zombies' textures and sounds, but their emissive eyes cease to function. I have tested the texture pack with base Complementary Reimagined, and it works there.

Here are some images to show the differences:
![2023-04-25_21 52 39](https://user-images.githubusercontent.com/33318750/234460439-254c4486-6c18-425a-b165-5b753aa899f4.png)
**Vanilla**

![2023-04-25_21 53 36](https://user-images.githubusercontent.com/33318750/234460477-e4269db5-82f5-47e7-9b12-f7730ac9e3dc.png)
**Rethinking Voxels** _(beta18d)_

![2023-04-25_21 53 59](https://user-images.githubusercontent.com/33318750/234460631-53903b9c-559e-4c6a-9df5-5ff6adb3d1b5.png)
**Complementary Reimagined** _(r2.1)_

_Current Setup:_
Minecraft - v1.19.4
Iris - v1.6.1
Sodium - v0.4.10+build.24
Entity Textures Features - v4.4.0 (for Emissive and Random textures)

**Comment by gri573** [comment]
emissive textures that use optifine's emissive texture format can't and will never work with rethinking voxels because the only information the shader receives about them is that there is a lot of light at a location. rethinking voxels calculates its own light, so it has to ignore that information because otherwise things would look weird
