### ISSUE TITLE
Can't customise modded light sources' emission colour

### ISSUE THREAD

**Issue by C-7007** [gri573/rethinking-voxels#164]
Hello! First, I have to say that I am beyond pleased with these shaders, they're brilliant.

I am, however, meeting a minor problem: I can't change the light colour of modded emissive blocks I add to the shader. I tried it with Additional Lanterns: after reloading the shaders, the modded lanterns are detected, emit light in their "on" state and do not in their "off" state, as they should, but this light remains white, and I cannot find the file in which I could put RGB values to fix that.

Can you help me with that, or redirect me to a previous issue that had a similar problem? 

Thank you!

**Comment by gri573** [comment]
adding customization options for modded lights would be completely unmaintainable because of the sheer amount of light-emitting blocks in various minecraft mods. currently, the shader does a heuristic to determine the light colour of a light based on its texture, but this can fail. if it does fail in a distracting way, you can remove its block ID from the line starting with `block.1234` in `shaders/block.properties` and add it to the line starting with `block.1235` instead to give it a neutral colour. alternatively, you can add the lights' block IDs to the lines containing the most similar vanilla light sources.
