### ISSUE TITLE
emissive ore texture pack with this shader doesn't work

### ISSUE THREAD

**Issue by Huybay1723** [gri573/rethinking-voxels#187]
I use visible ore texture pack ,ore doesn't  emiss light when I get close

**Comment by gri573** [comment]
yes, that is unfixable unless your texturepack uses the labPBR emissive format

**Comment by SinanAkkoyun** [comment]
@gri573 Hey, I tried this: https://www.curseforge.com/minecraft/texture-packs/avpbr-retextured

Which labPBR says is completely compatible, but it does not emit.

(I am asking because I need to render custom lines in a fabric mod and all renderlayers I tried do recieve shading and lighting, none of them is emissive)

**Comment by SinanAkkoyun** [comment]
I even made the _s texture of the diamond ore slightly transparent (which represents emissiveness) and nothing happens
