### ISSUE TITLE
Some light source don't emit light

### ISSUE THREAD

**Issue by atxoxx** [gri573/rethinking-voxels#33]
Hello ! 

Some light source from vanilla and mods don't emit lights at all 

![image](https://user-images.githubusercontent.com/4542633/214915913-d6ff5802-4ea1-4cc4-a2d2-f1cab1f08a2b.png)

**Comment by gri573** [comment]
hello. see #35 for information about adding new light sources to rethinking voxels. You may be better off adding that wall lantern to the lantern entry though, the thing you'd do differently for that compared to the regular way is that you find the line that contains `lantern` (`block.10560=lantern`) and add the ID to that instead of the line with `block.1234`
