### ISSUE TITLE
Strange Visual Glitch 

### ISSUE THREAD

**Issue by Ayreseraph** [gri573/rethinking-voxels#38]
there's this weird floating item bar shadow. If I fly up it starts projecting items on the ground beneath me.
[Image](https://cdn.discordapp.com/attachments/742835878451478670/1069519113359212585/2023-01-30_02.26.29.png) [Image](https://cdn.discordapp.com/attachments/742835878451478670/1069519999607242822/2023-01-30_02.30.26.png)

**Comment by gri573** [comment]
I think you may be using an outdated shader loader. what optifine/iris version do you use?

**Comment by Ayreseraph** [comment]
Updated the Optifine version to the newest one, now I get a giant black square shaded area.

**Comment by gri573** [comment]
what version is that? anything lower than G8 won't work, even if it's the latest version on the minecraft version you are using. if you are on minecraft 1.19.x, then it should work, although I'm not sure if it breaks on the optifine previews for 1.19.3. I usually recommend people to use iris if possible, because that's where I do my testing, so that applies to you as well unless you have specific reasons to use optifine.

**Comment by gri573** [comment]
I'll close this issue now, I'll reopen it if you come back to me with more information
