### ISSUE TITLE
Fluctuating (not smooth) blocklight values on multiple light sources

### ISSUE THREAD

**Issue by jeffswt** [gri573/rethinking-voxels#39]
Minimal repro scene (you'll have to need a lot of light sources):

![Sample](https://user-images.githubusercontent.com/18145331/215561536-c068be7a-a3b8-4eaa-bd49-fe910af6b070.png)

My shader config on commit `38f640f`:

```
OCCLUSION_CASCADE_COUNT=2
BLOCKLIGHT_CHECK_INTERVAL=10
INST_LP=true
PP_BL_SHADOWS=true
GENERATED_NORMALS=true
VXHEIGHT=12
```

**Comment by gri573** [comment]
the issue as a whole is a side effect of the fact that the shader needs to keep track of light source positions and can only do so for up to 3 per location. this may be changed in the future, but it is limited by the capabilities of the iris/optifine shader pipeline at the moment. the way the problem appears may have changed in the last few commits because I changed the light sorting algorithm to fix flickering. I'm going to try to make it look better though.

**Comment by jeffswt** [comment]
Yes I've seen a significant improvement through the past several weeks...
