### ISSUE TITLE
Does not seem to support light blocks

### ISSUE THREAD

**Issue by Speeder323** [gri573/rethinking-voxels#68]
![image](https://user-images.githubusercontent.com/61844671/218099647-d938f832-5297-4d7c-b247-fcaa134727fb.png)
While the item in your hand does technically glow because of dynamic handheld lighting, the light blocks themselves seem to emit no light at all.

Unless I'm just stupid, which is also a possibility.

**Comment by jeffswt** [comment]
Is this a vanilla block? If not you'll have to manually change the config, it's somewhere in the README.

**Comment by jeffswt** [comment]
I feel like it's missing from `shaders/block.properties`.

**Comment by gri573** [comment]
light blocks can theoretically be supported in the state where they are visible, i.e. when you hold a light block in your hand, but they are impossible to support in their invisible state because they aren't rendered, so the shader doesn't even get told they exist. I think that supporting them in their visible state isn't really worthwile
